<div align="right" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/ExploreAI_logos/Logo blue_dark.png"  style="width:25px" align="right";/>
</div>

# SELECT and SELECT WHERE
© ExploreAI Academy

In this walk-through we demonstrate how to get data out of a table using the SELECT statement.
We also show how to filter data using the where clause.

> ⚠️ This notebook will not run on Google Colab because it cannot connect to a local database. Please make sure that this notebook is running on the same local machine as your MySQL Workbench installation and MySQL `united_nations` database.

## Learning objectives

In this train, we will learn:
- How to use SELECT and SELECT DISTINCT to select columns.
- How to use WHERE to filter data based on a condition.
- Save results sets as new tables.

## Connecting to our MySQL database

Using our `Access_to_Basic_Services` table in our `united_nations` database we created in MySQL Workbench, we want to answer some questions about our dataset. We can apply the same queries we used in MySQL Workbench in this notebook if we connect to our MySQL server by running the cells below.

In [1]:
# Load and activate the SQL extension to allow us to execute SQL in a Jupyter notebook. 
# If you get an error here, make sure that mysql and pymysql are installed correctly. 

# %load_ext sql
%load_ext sql

In [3]:
# Establish a connection to the local database using the '%sql' magic command.
# Replace 'password' with our connection password and `db_name` with our database name. 
# If you get an error here, please make sure the database name or password is correct.

%sql mysql+pymysql://cybergod:example-password@localhost:3306/united_nations


To make a query, we add the `%%sql` command to the start of a cell, create one open line, then the query like below, and run the cell.

In [4]:
%%sql

SELECT 
    *
FROM
    Access_to_basic_services
LIMIT 5;

 * mysql+pymysql://cybergod:***@localhost:3306/united_nations
5 rows affected.

[('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2015, 94.67, 98, 17.542806, 184.39, 2699700, 4.93),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2016, 94.67, 98, 17.794055, 137.28, 2699700, 4.96),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2017, 95.0, 98, 18.037776, 166.81, 2699700, 4.9),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2018, 95.0, 98, 18.276452, 179.34, 2699700, 4.85),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2019, 95.0, 98, 18.513673, 181.67, 2699700, 4.8)]

## Exercise

Suppose we want to find out which country had the lowest percentage of people with access to managed drinking water services in 2020.

### 1. Exploring the database

Use the `SELECT` statement to display all the columns from the `Access_to_Basic_Services` table. This will help us get a feel for the data we're working with.

In [10]:
%%sql
# Add your code here
# USE united_nations;
SELECT 
* 
FROM 
Access_to_basic_services
LIMIT 100;

 * mysql+pymysql://cybergod:***@localhost:3306/united_nations
100 rows affected.

[('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2015, 94.67, 98, 17.542806, 184.39, 2699700, 4.93),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2016, 94.67, 98, 17.794055, 137.28, 2699700, 4.96),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2017, 95.0, 98, 18.037776, 166.81, 2699700, 4.9),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2018, 95.0, 98, 18.276452, 179.34, 2699700, 4.85),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2019, 95.0, 98, 18.513673, 181.67, 2699700, 4.8),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2020, 95.0, 98, 18.755666, 171.08, 2699700, 4.89),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2015, 89.67, 97, None, None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2016, 90.33, 97, None, None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2017, 91.0, 97, None, None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2018, 91.33, 97, None, None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2019, 91.67, 97, None, None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2020, 92.67, 98, None, None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Tajikistan', 2015, 80.33, 95, 8.524063, 8.27, 138790, None),
 ('Central and Southern Asia', 'Central Asia', 'Tajikistan', 2016, 81.33, 95, 8.725318, 6.99, 138790, 6.9),
 ('Central and Southern Asia', 'Central Asia', 'Tajikistan', 2017, 82.33, 96, 8.925525, 7.54, 138790, None),
 ('Central and Southern Asia', 'Central Asia', 'Tajikistan', 2018, 83.33, 96, 9.128132, 7.77, 138790, None),
 ('Central and Southern Asia', 'Central Asia', 'Tajikistan', 2019, 85.0, 96, 9.337003, 8.3, 138790, None),
 ('Central and Southern Asia', 'Central Asia', 'Tajikistan', 2020, 85.0, 96, 9.543207, 8.13, 138790, None),
 ('Central and Southern Asia', 'Central Asia', 'Turkmenistan', 2015, 97.67, 97, 5.766431, 35.8, 469930, None),
 ('Central and Southern Asia', 'Central Asia', 'Turkmenistan', 2016, 98.0, 98, 5.868561, 36.17, 469930, None),
 ('Central and Southern Asia', 'Central Asia', 'Turkmenistan', 2017, 98.67, 98, 5.968383, 37.93, 469930, None),
 ('Central and Southern Asia', 'Central Asia', 'Turkmenistan', 2018, 99.33, 99, 6.065066, 40.77, 469930, None),
 ('Central and Southern Asia', 'Central Asia', 'Turkmenistan', 2019, 100.0, 99, 6.15842, 45.23, 469930, None),
 ('Central and Southern Asia', 'Central Asia', 'Turkmenistan', 2020, 100.0, 99, 6.250438, None, 469930, None),
 ('Central and Southern Asia', 'Central Asia', 'Uzbekistan', 2015, 97.67, 100, 31.2989, 86.2, 440600, 5.15),
 ('Central and Southern Asia', 'Central Asia', 'Uzbekistan', 2016, 97.67, 100, 31.8479, 86.14, 440591, 5.16),
 ('Central and Southern Asia', 'Central Asia', 'Uzbekistan', 2017, 98.0, 100, 32.3886, 62.08, 440588, 5.83),
 ('Central and Southern Asia', 'Central Asia', 'Uzbekistan', 2018, 98.0, 100, 32.9561, 52.63, 440587, 9.35),
 ('Central and Southern Asia', 'Central Asia', 'Uzbekistan', 2019, 98.0, 100, 33.58035, 59.91, 440555, 8.98),
 ('Central and Southern Asia', 'Central Asia', 'Uzbekistan', 2020, 98.0, 100, 34.23205, 59.89, 440650, 5.29),
 ('Central and Southern Asia', 'Southern Asia', 'Afghanistan', 2015, 67.0, 46, 33.753499, 20.0, 652230, None),
 ('Central and Southern Asia', 'Southern Asia', 'Afghanistan', 2016, 69.67, 47, 34.636207, 18.02, 652230, None),
 ('Central and Southern Asia', 'Southern Asia', 'Afghanistan', 2017, 72.33, 49, 35.643418, 18.9, 652230, 11.18),
 ('Central and Southern Asia', 'Southern Asia', 'Afghanistan', 2018, 75.33, 51, 36.686784, 18.42, 652230, None),
 ('Central and Southern Asia', 'Southern Asia', 'Afghanistan', 2019, 78.0, 52, 37.769499, 18.9, 652230, None),
 ('Central and Southern Asia', 'Southern Asia', 'Afghanistan', 2020, 80.33, 54, 38.97223, 20.14, 652230, 11.71),
 ('Central and Southern Asia', 'Southern Asia', 'Bangladesh', 2015, 97.33, 47, 157.83, 195.08, 130170, None),
 ('Central and Southern Asia', 'Southern Asia', 'Bangladesh', 2016, 97.33, 49, 159.784568, 265.24, 130170, 4.35),
 ('Central and Southern Asia', 'Southern Asia', 'Bangladesh', 2017, 97.33, 50, 161.793964, 293.75, 130170, 4.37),
 ('Central and Southern Asia', 'Southern Asia', 'Bangladesh', 2018, 97.33, 51, 163.683958, 321.38, 130170, None),
 ('Central and Southern Asia', 'Southern Asia', 'Bangladesh', 2019, 97.67, 53, 165.516222, 351.24, 130170, None),
 ('Central and Southern Asia', 'Southern Asia', 'Bangladesh', 2020, 97.67, 54, 167.420951, 373.9, 130170, None),
 ('Central and Southern Asia', 'Southern Asia', 'Bhutan', 2015, 96.33, 71, 0.743274, 2.0, 38117, 2.45),
 ('Central and Southern Asia', 'Southern Asia', 'Bhutan', 2016, 97.0, 72, 0.749761, 2.16, 38144, None),
 ('Central and Southern Asia', 'Southern Asia', 'Bhutan', 2017, 97.33, 73, 0.756121, 2.45, 38144, None),
 ('Central and Southern Asia', 'Southern Asia', 'Bhutan', 2018, 97.33, 74, 0.762096, 2.45, 38140, 3.35),
 ('Central and Southern Asia', 'Southern Asia', 'Bhutan', 2019, 97.33, 75, 0.767459, 2.54, 38140, 2.72),
 ('Central and Southern Asia', 'Southern Asia', 'Bhutan', 2020, 97.33, 77, 0.772506, 2.33, 38140, 5.03),
 ('Central and Southern Asia', 'Southern Asia', 'India', 2015, 89.0, 59, 1322.866505, 2103.59, 2973190, None),
 ('Central and Southern Asia', 'Southern Asia', 'India', 2016, 89.33, 62, 1338.63634, 2294.8, 2973190, None),
 ('Central and Southern Asia', 'Southern Asia', 'India', 2017, 90.0, 64, 1354.19568, 2651.47, 2973190, None),
 ('Central and Southern Asia', 'Southern Asia', 'India', 2018, 90.33, 67, 1369.003306, 2702.93, 2973190, 7.65),
 ('Central and Southern Asia', 'Southern Asia', 'India', 2019, 90.67, 70, 1383.11205, 2831.55, 2973190, 6.51),
 ('Central and Southern Asia', 'Southern Asia', 'India', 2020, 91.0, 72, 1396.387127, 2667.69, 2973190, 7.86),
 ('Central and Southern Asia', 'Southern Asia', 'Iran (Islamic Republic of)', 2015, 95.67, 86, None, None, None, None),
 ('Central and Southern Asia', 'Southern Asia', 'Iran (Islamic Republic of)', 2016, 96.0, 87, None, None, None, None),
 ('Central and Southern Asia', 'Southern Asia', 'Iran (Islamic Republic of)', 2017, 96.33, 88, None, None, None, None),
 ('Central and Southern Asia', 'Southern Asia', 'Iran (Islamic Republic of)', 2018, 96.33, 88, None, None, None, None),
 ('Central and Southern Asia', 'Southern Asia', 'Iran (Islamic Republic of)', 2019, 96.33, 88, None, None, None, None),
 ('Central and Southern Asia', 'Southern Asia', 'Iran (Islamic Republic of)', 2020, 96.67, 88, None, None, None, None),
 ('Central and Southern Asia', 'Southern Asia', 'Maldives', 2015, 99.0, 95, 0.435582, 4.11, 300, None),
 ('Central and Southern Asia', 'Southern Asia', 'Maldives', 2016, 99.0, 95, 0.454252, 4.38, 300, 5.77),
 ('Central and Southern Asia', 'Southern Asia', 'Maldives', 2017, 99.33, 96, 0.472442, 4.75, 300, None),
 ('Central and Southern Asia', 'Southern Asia', 'Maldives', 2018, 99.33, 98, 0.489758, 5.3, 300, None),
 ('Central and Southern Asia', 'Southern Asia', 'Maldives', 2019, 99.67, 98, 0.504508, 5.61, 300, 4.56),
 ('Central and Southern Asia', 'Southern Asia', 'Maldives', 2020, 99.67, 99, 0.514438, 3.75, 300, None),
 ('Central and Southern Asia', 'Southern Asia', 'Nepal', 2015, 88.33, 60, 27.610325, 24.36, 143350, 3.1),
 ('Central and Southern Asia', 'Southern Asia', 'Nepal', 2016, 88.67, 63, 27.861186, 24.52, 143350, None),
 ('Central and Southern Asia', 'Southern Asia', 'Nepal', 2017, 89.0, 67, 28.183426, 28.97, 143350, 10.66),
 ('Central and Southern Asia', 'Southern Asia', 'Nepal', 2018, 89.33, 70, 28.506712, 33.11, 143350, None),
 ('Central and Southern Asia', 'Southern Asia', 'Nepal', 2019, 90.0, 73, 28.832496, 34.19, 143350, None),
 ('Central and Southern Asia', 'Southern Asia', 'Nepal', 2020, 90.0, 77, 29.348627, 33.43, 143350, None),
 ('Central and Southern Asia', 'Southern Asia', 'Pakistan', 2015, 90.0, 62, 210.969298, 270.56, 770880, 3.57),
 ('Central and Southern Asia', 'Southern Asia', 'Pakistan', 2016, 90.0, 63, 213.52484, 313.63, 770880, None),
 ('Central and Southern Asia', 'Southern Asia', 'Pakistan', 2017, 90.33, 65, 216.379655, 339.21, 770880, None),
 ('Central and Southern Asia', 'Southern Asia', 'Pakistan', 2018, 90.33, 67, 219.731479, 356.13, 770880, 4.08),
 ('Central and Southern Asia', 'Southern Asia', 'Pakistan', 2019, 90.33, 69, 223.29328, 320.91, 770880, 4.83),
 ('Central and Southern Asia', 'Southern Asia', 'Pakistan', 2020, 90.67, 70, 227.196741, 300.43, 770880, None),
 ('Central and Southern Asia', 'Southern Asia', 'Sri Lanka', 2015, 92.0, 91, 20.97, 85.14, 61893, 4.52),
 ('Central and Southern Asia', 'Southern Asia', 'Sri Lanka', 2016, 93.0, 92, 21.203, 88.01, 61893, 4.24),
 ('Central and Southern Asia', 'Southern Asia', 'Sri Lanka', 2017, 93.67, 93, 21.444, 94.38, 61893, 4.05),
 ('Central and Southern Asia', 'Southern Asia', 'Sri Lanka', 2018, 94.33, 94, 21.67, 94.49, 61864, 4.32),
 ('Central and Southern Asia', 'Southern Asia', 'Sri Lanka', 2019, 94.33, 94, 21.803, 89.01, 61864, 4.67),
 ('Central and Southern Asia', 'Southern Asia', 'Sri Lanka', 2020, 94.33, 94, 21.919, 85.35, 61860, 5.36),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', 'China', 2015, 91.33, 84, 1379.86, 11061.55, 9424701, None),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', 'China', 2016, 91.33, 86, 1387.79, 11233.28, 9424701, None),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', 'China', 2017, 92.0, 87, 1396.215, 12310.41, 9424701, 3.9),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', 'China', 2018, 92.67, 88, 1402.76, 13894.82, 9424703, 4.93),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', 'China', 2019, 93.33, 90, 1407.745, 14279.94, 9424703, 5.15),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', 'China', 2020, 93.67, 92, 1411.1, 14687.67, 9424703, 5.61),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', "Democratic People's Republic of Korea", 2015, 94.67, 80, None, None, None, None),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', "Democratic People's Republic of Korea", 2016, 94.33, 81, None, None, None, None),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', "Democratic People's Republic of Korea", 2017, 94.0, 82, None, None, None, None),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', "Democratic People's Republic of Korea", 2018, 93.33, 83, None, None, None, None),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', "Democratic People's Republic of Korea", 2019, 93.33, 83, None, None, None, None),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', "Democratic People's Republic of Korea", 2020, 93.33, 83, None, None, None, None),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', 'Japan', 2015, 99.0, 100, 127.141, 4444.93, 364500, 3.39),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', 'Japan', 2016, 99.0, 100, 127.076, 5003.68, 364500, 3.13),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', 'Japan', 2017, 99.0, 100, 126.972, 4930.84, 364500, 2.82),
 ('Eastern and South-Eastern Asia', 'Eastern Asia', 'Japan', 2018, 99.0, 100, 126.811, 5037.84, 364500, 2.47)]

The previous query may return a large number of rows, which could slow down our system. Modify the query to limit the number of rows returned to 10.

In [11]:
%%sql
SELECT 
* 
FROM 
Access_to_basic_services
LIMIT 10;

 * mysql+pymysql://cybergod:***@localhost:3306/united_nations
10 rows affected.

[('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2015, 94.67, 98, 17.542806, 184.39, 2699700, 4.93),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2016, 94.67, 98, 17.794055, 137.28, 2699700, 4.96),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2017, 95.0, 98, 18.037776, 166.81, 2699700, 4.9),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2018, 95.0, 98, 18.276452, 179.34, 2699700, 4.85),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2019, 95.0, 98, 18.513673, 181.67, 2699700, 4.8),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2020, 95.0, 98, 18.755666, 171.08, 2699700, 4.89),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2015, 89.67, 97, None, None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2016, 90.33, 97, None, None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2017, 91.0, 97, None, None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2018, 91.33, 97, None, None, None, None)]

### 2. Unique country names
Extract a list of unique country names in the database.

In [13]:
%%sql
SELECT DISTINCT
    Country_name
FROM 
Access_to_basic_services

 * mysql+pymysql://cybergod:***@localhost:3306/united_nations
182 rows affected.

[('Kazakhstan',),
 ('Kyrgyzstan',),
 ('Tajikistan',),
 ('Turkmenistan',),
 ('Uzbekistan',),
 ('Afghanistan',),
 ('Bangladesh',),
 ('Bhutan',),
 ('India',),
 ('Iran (Islamic Republic of)',),
 ('Maldives',),
 ('Nepal',),
 ('Pakistan',),
 ('Sri Lanka',),
 ('China',),
 ("Democratic People's Republic of Korea",),
 ('Japan',),
 ('Mongolia',),
 ('Republic of Korea',),
 ('Brunei Darussalam',),
 ('Cambodia',),
 ('Indonesia',),
 ("Lao People's Democratic Republic",),
 ('Malaysia',),
 ('Myanmar',),
 ('Philippines',),
 ('Singapore',),
 ('Thailand',),
 ('Timor-Leste',),
 ('Viet Nam',),
 ('Bermuda',),
 ('Canada',),
 ('Greenland',),
 ('Saint Pierre and Miquelon',),
 ('United States of America',),
 ('Anguilla',),
 ('Antigua and Barbuda',),
 ('Aruba',),
 ('Bahamas',),
 ('Barbados',),
 ('British Virgin Islands',),
 ('Cayman Islands',),
 ('Cuba',),
 ('Curaçao',),
 ('Dominica',),
 ('Dominican Republic',),
 ('Grenada',),
 ('Guadeloupe',),
 ('Haiti',),
 ('Jamaica',),
 ('Martinique',),
 ('Montserrat',),
 ('Puerto Rico',),
 ('Saint Barthélemy',),
 ('Saint Kitts and Nevis',),
 ('Saint Lucia',),
 ('Saint Martin (French Part)',),
 ('Saint Vincent and the Grenadines',),
 ('Sint Maarten (Dutch part)',),
 ('Trinidad and Tobago',),
 ('Turks and Caicos Islands',),
 ('United States Virgin Islands',),
 ('Belize',),
 ('Costa Rica',),
 ('El Salvador',),
 ('Guatemala',),
 ('Honduras',),
 ('Mexico',),
 ('Nicaragua',),
 ('Panama',),
 ('Argentina',),
 ('Bolivia (Plurinational State of)',),
 ('Brazil',),
 ('Chile',),
 ('Colombia',),
 ('Ecuador',),
 ('Falkland Islands (Malvinas)',),
 ('French Guiana',),
 ('Guyana',),
 ('Paraguay',),
 ('Peru',),
 ('Suriname',),
 ('Uruguay',),
 ('Venezuela (Bolivarian Republic of)',),
 ('Algeria',),
 ('Egypt',),
 ('Libya',),
 ('Morocco',),
 ('Sudan',),
 ('Tunisia',),
 ('Armenia',),
 ('Azerbaijan',),
 ('Bahrain',),
 ('Cyprus',),
 ('Georgia',),
 ('Iraq',),
 ('Israel',),
 ('Jordan',),
 ('Kuwait',),
 ('Lebanon',),
 ('Oman',),
 ('Qatar',),
 ('Saudi Arabia',),
 ('State of Palestine',),
 ('Syrian Arab Republic',),
 ('Türkiye',),
 ('United Arab Emirates',),
 ('Yemen',),
 ('Australia',),
 ('New Zealand',),
 ('Fiji',),
 ('New Caledonia',),
 ('Papua New Guinea',),
 ('Solomon Islands',),
 ('Vanuatu',),
 ('Guam',),
 ('Kiribati',),
 ('Marshall Islands',),
 ('Micronesia (Federated States of)',),
 ('Nauru',),
 ('Northern Mariana Islands',),
 ('Palau',),
 ('American Samoa',),
 ('Cook Islands',),
 ('French Polynesia',),
 ('Niue',),
 ('Samoa',),
 ('Tokelau',),
 ('Tonga',),
 ('Tuvalu',),
 ('Wallis and Futuna Islands',),
 ('Burundi',),
 ('Comoros',),
 ('Djibouti',),
 ('Eritrea',),
 ('Ethiopia',),
 ('Kenya',),
 ('Madagascar',),
 ('Malawi',),
 ('Mauritius',),
 ('Mayotte',),
 ('Mozambique',),
 ('Rwanda',),
 ('Réunion',),
 ('Seychelles',),
 ('Somalia',),
 ('South Sudan',),
 ('Uganda',),
 ('United Republic of Tanzania',),
 ('Zambia',),
 ('Zimbabwe',),
 ('Angola',),
 ('Cameroon',),
 ('Central African Republic',),
 ('Chad',),
 ('Congo',),
 ('Democratic Republic of the Congo',),
 ('Equatorial Guinea',),
 ('Gabon',),
 ('Sao Tome and Principe',),
 ('Botswana',),
 ('Eswatini',),
 ('Lesotho',),
 ('Namibia',),
 ('South Africa',),
 ('Benin',),
 ('Burkina Faso',),
 ('Cabo Verde',),
 ("Côte d'Ivoire",),
 ('Gambia',),
 ('Ghana',),
 ('Guinea',),
 ('Guinea-Bissau',),
 ('Liberia',),
 ('Mali',),
 ('Mauritania',),
 ('Niger',),
 ('Nigeria',),
 ('Saint Helena',),
 ('Senegal',),
 ('Sierra Leone',),
 ('Togo',)]

Create a new table called `Country_list` and save the unique country names into this table.

In [20]:
%%sql
CREATE TABLE Country_list(Country VARCHAR(25));

INSERT INTO Country_list(Country)
SELECT DISTINCT 
    Country_name
FROM 
    Access_to_basic_services;

 * mysql+pymysql://cybergod:***@localhost:3306/united_nations
(pymysql.err.OperationalError) (1050, "Table 'Country_list' already exists")
[SQL: CREATE TABLE Country_list(Country VARCHAR(25));]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [21]:
%%sql
SELECT 
* 
FROM 
Country_list;

 * mysql+pymysql://cybergod:***@localhost:3306/united_nations
182 rows affected.

[('Kazakhstan',),
 ('Kyrgyzstan',),
 ('Tajikistan',),
 ('Turkmenistan',),
 ('Uzbekistan',),
 ('Afghanistan',),
 ('Bangladesh',),
 ('Bhutan',),
 ('India',),
 ('Iran (Islamic Republic of)',),
 ('Maldives',),
 ('Nepal',),
 ('Pakistan',),
 ('Sri Lanka',),
 ('China',),
 ("Democratic People's Republic of Korea",),
 ('Japan',),
 ('Mongolia',),
 ('Republic of Korea',),
 ('Brunei Darussalam',),
 ('Cambodia',),
 ('Indonesia',),
 ("Lao People's Democratic Republic",),
 ('Malaysia',),
 ('Myanmar',),
 ('Philippines',),
 ('Singapore',),
 ('Thailand',),
 ('Timor-Leste',),
 ('Viet Nam',),
 ('Bermuda',),
 ('Canada',),
 ('Greenland',),
 ('Saint Pierre and Miquelon',),
 ('United States of America',),
 ('Anguilla',),
 ('Antigua and Barbuda',),
 ('Aruba',),
 ('Bahamas',),
 ('Barbados',),
 ('British Virgin Islands',),
 ('Cayman Islands',),
 ('Cuba',),
 ('Curaçao',),
 ('Dominica',),
 ('Dominican Republic',),
 ('Grenada',),
 ('Guadeloupe',),
 ('Haiti',),
 ('Jamaica',),
 ('Martinique',),
 ('Montserrat',),
 ('Puerto Rico',),
 ('Saint Barthélemy',),
 ('Saint Kitts and Nevis',),
 ('Saint Lucia',),
 ('Saint Martin (French Part)',),
 ('Saint Vincent and the Grenadines',),
 ('Sint Maarten (Dutch part)',),
 ('Trinidad and Tobago',),
 ('Turks and Caicos Islands',),
 ('United States Virgin Islands',),
 ('Belize',),
 ('Costa Rica',),
 ('El Salvador',),
 ('Guatemala',),
 ('Honduras',),
 ('Mexico',),
 ('Nicaragua',),
 ('Panama',),
 ('Argentina',),
 ('Bolivia (Plurinational State of)',),
 ('Brazil',),
 ('Chile',),
 ('Colombia',),
 ('Ecuador',),
 ('Falkland Islands (Malvinas)',),
 ('French Guiana',),
 ('Guyana',),
 ('Paraguay',),
 ('Peru',),
 ('Suriname',),
 ('Uruguay',),
 ('Venezuela (Bolivarian Republic of)',),
 ('Algeria',),
 ('Egypt',),
 ('Libya',),
 ('Morocco',),
 ('Sudan',),
 ('Tunisia',),
 ('Armenia',),
 ('Azerbaijan',),
 ('Bahrain',),
 ('Cyprus',),
 ('Georgia',),
 ('Iraq',),
 ('Israel',),
 ('Jordan',),
 ('Kuwait',),
 ('Lebanon',),
 ('Oman',),
 ('Qatar',),
 ('Saudi Arabia',),
 ('State of Palestine',),
 ('Syrian Arab Republic',),
 ('Türkiye',),
 ('United Arab Emirates',),
 ('Yemen',),
 ('Australia',),
 ('New Zealand',),
 ('Fiji',),
 ('New Caledonia',),
 ('Papua New Guinea',),
 ('Solomon Islands',),
 ('Vanuatu',),
 ('Guam',),
 ('Kiribati',),
 ('Marshall Islands',),
 ('Micronesia (Federated States of)',),
 ('Nauru',),
 ('Northern Mariana Islands',),
 ('Palau',),
 ('American Samoa',),
 ('Cook Islands',),
 ('French Polynesia',),
 ('Niue',),
 ('Samoa',),
 ('Tokelau',),
 ('Tonga',),
 ('Tuvalu',),
 ('Wallis and Futuna Islands',),
 ('Burundi',),
 ('Comoros',),
 ('Djibouti',),
 ('Eritrea',),
 ('Ethiopia',),
 ('Kenya',),
 ('Madagascar',),
 ('Malawi',),
 ('Mauritius',),
 ('Mayotte',),
 ('Mozambique',),
 ('Rwanda',),
 ('Réunion',),
 ('Seychelles',),
 ('Somalia',),
 ('South Sudan',),
 ('Uganda',),
 ('United Republic of Tanzania',),
 ('Zambia',),
 ('Zimbabwe',),
 ('Angola',),
 ('Cameroon',),
 ('Central African Republic',),
 ('Chad',),
 ('Congo',),
 ('Democratic Republic of the Congo',),
 ('Equatorial Guinea',),
 ('Gabon',),
 ('Sao Tome and Principe',),
 ('Botswana',),
 ('Eswatini',),
 ('Lesotho',),
 ('Namibia',),
 ('South Africa',),
 ('Benin',),
 ('Burkina Faso',),
 ('Cabo Verde',),
 ("Côte d'Ivoire",),
 ('Gambia',),
 ('Ghana',),
 ('Guinea',),
 ('Guinea-Bissau',),
 ('Liberia',),
 ('Mali',),
 ('Mauritania',),
 ('Niger',),
 ('Nigeria',),
 ('Saint Helena',),
 ('Senegal',),
 ('Sierra Leone',),
 ('Togo',)]

### 3. Selecting specific fields

Select the `country_name`, `time_period`, and `pct_managed_drinking_water_services` fields from the `Access_to_Basic_Services` table.

In [29]:
%%sql
# # use united_nations;
SELECT
    Country_name, 
    Time_period,
    Pct_managed_drinking_water_services
FROM 
    Access_to_basic_services
LIMIT 20;

 * mysql+pymysql://cybergod:***@localhost:3306/united_nations
20 rows affected.

[('Kazakhstan', 2015, 94.67),
 ('Kazakhstan', 2016, 94.67),
 ('Kazakhstan', 2017, 95.0),
 ('Kazakhstan', 2018, 95.0),
 ('Kazakhstan', 2019, 95.0),
 ('Kazakhstan', 2020, 95.0),
 ('Kyrgyzstan', 2015, 89.67),
 ('Kyrgyzstan', 2016, 90.33),
 ('Kyrgyzstan', 2017, 91.0),
 ('Kyrgyzstan', 2018, 91.33),
 ('Kyrgyzstan', 2019, 91.67),
 ('Kyrgyzstan', 2020, 92.67),
 ('Tajikistan', 2015, 80.33),
 ('Tajikistan', 2016, 81.33),
 ('Tajikistan', 2017, 82.33),
 ('Tajikistan', 2018, 83.33),
 ('Tajikistan', 2019, 85.0),
 ('Tajikistan', 2020, 85.0),
 ('Turkmenistan', 2015, 97.67),
 ('Turkmenistan', 2016, 98.0)]

Rename the `pct_managed_drinking_water_services` field to `pct_access_to_water` in your query results.

In [31]:
%%sql
# Add your code here
SELECT
    Country_name, 
    Time_period,
    Pct_managed_drinking_water_services as pct_access_to_water
FROM 
    Access_to_basic_services
LIMIT 20;

 * mysql+pymysql://cybergod:***@localhost:3306/united_nations
20 rows affected.

[('Kazakhstan', 2015, 94.67),
 ('Kazakhstan', 2016, 94.67),
 ('Kazakhstan', 2017, 95.0),
 ('Kazakhstan', 2018, 95.0),
 ('Kazakhstan', 2019, 95.0),
 ('Kazakhstan', 2020, 95.0),
 ('Kyrgyzstan', 2015, 89.67),
 ('Kyrgyzstan', 2016, 90.33),
 ('Kyrgyzstan', 2017, 91.0),
 ('Kyrgyzstan', 2018, 91.33),
 ('Kyrgyzstan', 2019, 91.67),
 ('Kyrgyzstan', 2020, 92.67),
 ('Tajikistan', 2015, 80.33),
 ('Tajikistan', 2016, 81.33),
 ('Tajikistan', 2017, 82.33),
 ('Tajikistan', 2018, 83.33),
 ('Tajikistan', 2019, 85.0),
 ('Tajikistan', 2020, 85.0),
 ('Turkmenistan', 2015, 97.67),
 ('Turkmenistan', 2016, 98.0)]

### 4. Filtering and sorting data

Modify your query to only display data for the year `2020`.

In [33]:
%%sql
# Add your code here
SELECT
    Country_name, 
    Time_period,
    Pct_managed_drinking_water_services
FROM 
    Access_to_basic_services
WHERE Time_period=2020
LIMIT 20;

 * mysql+pymysql://cybergod:***@localhost:3306/united_nations
20 rows affected.

[('Kazakhstan', 2020, 95.0),
 ('Kyrgyzstan', 2020, 92.67),
 ('Tajikistan', 2020, 85.0),
 ('Turkmenistan', 2020, 100.0),
 ('Uzbekistan', 2020, 98.0),
 ('Afghanistan', 2020, 80.33),
 ('Bangladesh', 2020, 97.67),
 ('Bhutan', 2020, 97.33),
 ('India', 2020, 91.0),
 ('Iran (Islamic Republic of)', 2020, 96.67),
 ('Maldives', 2020, 99.67),
 ('Nepal', 2020, 90.0),
 ('Pakistan', 2020, 90.67),
 ('Sri Lanka', 2020, 94.33),
 ('China', 2020, 93.67),
 ("Democratic People's Republic of Korea", 2020, 93.33),
 ('Japan', 2020, 99.0),
 ('Mongolia', 2020, 81.0),
 ('Republic of Korea', 2020, 100.0),
 ('Brunei Darussalam', 2020, 100.0)]

The previous query may return a large number of rows, which could slow down our system. Modify the query to limit the number of rows returned to 10.

In [37]:
%%sql
# Add your code here
SELECT
    Country_name, 
    Time_period,
    Pct_managed_drinking_water_services as pct_access_to_water
FROM 
    Access_to_basic_services
WHERE Time_period=2020
ORDER BY pct_access_to_water ASC
#Since we cannot sort like we did in the MySQL GUI, we have to use SQL. Just add your code before this line, and this line will order your results. 
LIMIT 10;

 * mysql+pymysql://cybergod:***@localhost:3306/united_nations
10 rows affected.

[('Central African Republic', 2020, 38.33),
 ('Democratic Republic of the Congo', 2020, 47.67),
 ('South Sudan', 2020, 48.33),
 ('Angola', 2020, 52.33),
 ('Chad', 2020, 52.67),
 ('Burkina Faso', 2020, 53.33),
 ('Madagascar', 2020, 56.33),
 ('Papua New Guinea', 2020, 56.67),
 ('Niger', 2020, 57.33),
 ('Somalia', 2020, 57.33)]

In [41]:
%%sql
SHOW COLUMNS
FROM 
    Access_to_basic_services;

 * mysql+pymysql://cybergod:***@localhost:3306/united_nations
10 rows affected.

[('Region', 'text', 'YES', '', None, ''),
 ('Sub_region', 'text', 'YES', '', None, ''),
 ('Country_name', 'text', 'YES', '', None, ''),
 ('Time_period', 'int', 'YES', '', None, ''),
 ('Pct_managed_drinking_water_services', 'double', 'YES', '', None, ''),
 ('Pct_managed_sanitation_services', 'int', 'YES', '', None, ''),
 ('Est_population_in_millions', 'double', 'YES', '', None, ''),
 ('Est_gdp_in_billions', 'double', 'YES', '', None, ''),
 ('Land_area', 'int', 'YES', '', None, ''),
 ('Pct_unemployment', 'double', 'YES', '', None, '')]

And there is the answer at the top:

In [ ]:
#Answer:38.33

## Solutions

### 1. Exploring the database

Use the `SELECT` statement to display all the columns from the `Access_to_Basic_Services` table. This will help us get a feel for the data we're working with.

In [ ]:
%%sql

SELECT 
    * 
FROM 
    united_nations.Access_to_Basic_Services
LIMIT 30;

The previous query may return a large number of rows, which could slow down our system. Modify the query to limit the number of rows returned to 10.

In [ ]:
%%sql

SELECT 
    * 
FROM 
    united_nations.Access_to_Basic_Services
LIMIT 10;

### 2. Unique country names
Extract a list of unique country names in the database.

In [ ]:
%%sql

SELECT DISTINCT 
    Country_name 
FROM 
    united_nations.Access_to_Basic_Services
    LIMIT 20;

Create a new table called `Country_list` and save the unique country names into this table.

In [ ]:
%%sql

CREATE TABLE Country_list(Country VARCHAR(255));
INSERT INTO Country_list(Country)
SELECT DISTINCT 
    Country_name 
FROM 
    united_nations.Access_to_Basic_Services;

### 3. Selecting specific fields

Select the `country_name`, `time_period`, and `pct_managed_drinking_water_services` fields from the `Access_to_Basic_Services` table.

In [ ]:
%%sql

SELECT 
    country_name, 
    time_period, 
    pct_managed_drinking_water_services 
FROM 
    united_nations.Access_to_Basic_Services
LIMIT 20;

Rename the `pct_managed_drinking_water_services` field to `pct_access_to_water` in your query results.

In [ ]:
%%sql

SELECT 
    country_name, 
    time_period, 
    pct_managed_drinking_water_services AS pct_access_to_water
FROM 
    united_nations.Access_to_Basic_Services
LIMIT 20

### 4. Filtering and sorting data

Modify your query to only display data for the year 2020.

In [ ]:
%%sql

SELECT 
    country_name, 
    time_period, 
    pct_managed_drinking_water_services AS pct_access_to_water
FROM 
    united_nations.Access_to_Basic_Services 
WHERE 
    Time_period = 2020
LIMIT 100;

The previous query may return a large number of rows, which could slow down our system. Modify the query to limit the number of rows returned to 10.

In [ ]:
%%sql

SELECT 
    country_name, 
    time_period, 
    pct_managed_drinking_water_services AS pct_access_to_water
FROM 
    united_nations.Access_to_Basic_Services 
WHERE 
    Time_period = 2020
ORDER BY pct_access_to_water
LIMIT 10;

## Summary
Congratulations! You have used SQL commands to filter and sort data to answer a specific question. Please review your results and think about what other questions could be answered with this data.

#  

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/ExploreAI_logos/EAI_Blue_Dark.png"  style="width:200px";/>
</div>